### ISSUE TITLE
应用可能启动不了

### ISSUE THREAD

**Issue by wangyuebanzi** [ywp0919/SwitchIconDemo#2]
![image](https://user-images.githubusercontent.com/30208125/65401081-67866680-ddf8-11e9-9693-8ed2d7664ed5.png)
这样设置完好像并不能解决外界显示调用MainActivity 出现启动错误的问题吧

**Comment by ywp0919** [comment]
@wangyuebanzi 是的，我注释那有说明这个enable为false后就不能再显式intent调用了呢，显式调用会有报错。
